#! /bin/bash
# script to run teqc and create skyplot or recplot from snr values
# usage: qcplot rinex_observation_file rinex_navigation_file type
#    rinex_observation_file: ssssddds.yyo, ssss=station id, ddd=day of year, s=session, yy=year
#    rinex_navigation_file 
#    type: sn1/sn2, default is sn1
# *** start of customizable part ***
TMPPATH=/tmp/
TEMPLATEPATH=./
SKY=skyplot.plt
REC=recplot.plt
SKYTEMPLATE=${TEMPLATEPATH}${SKY}
RECTEMPLATE=${TEMPLATEPATH}${REC}
# *** end of customizable part ***
if [ $# -lt 3 ]; then
	echo "usage: qcplot2 rinex_observation_file rinex_navigation_file type"
    echo "too few arguments"
	exit -1
fi
if [ ! -f $1 ]; then
    echo "rinex observation file not found"
    exit -2
fi 
if [ ! -f $2 ]; then
    echo "rinex navigation file not found"
    exit -3
fi
if [ ${#1} != 12 ]; then
    echo "rinex observation filename should have 12 character"
    echo $1 "has" ${#1} "character"
    exit -4
fi
if [ "$3" == "sn2" ]; then
    echo $3
    typ0="sn2"
    typ="snr2"
else
    typ0="sn1"    
    typ="snr1"
fi  
if [ ! -f $SKYTEMPLATE ]; then
	echo "skyplot template not found: $SKYTEMPLATE"
	exit -5
fi
if [ ! -f $RECTEMPLATE ]; then
	echo "recplot template not found: $RECTEMPLATE"
	exit -6
fi
station=${1::4} # station name: first four characters in rinex observation filename
doy=${1:4:3} # day of year: next three characters in rinex observation filename
session=${1:7:1} # day of year: next three characters in rinex observation filename
year=${1:9:2} # day of year: next three characters in rinex observation filename
year=20$year
OF=$RANDOM
OF1=${TMPPATH}${OF}.txt
OF2=${TMPPATH}${OF}.out
OF3=${TMPPATH}${OF}.rep
SKYPLT=${TMPPATH}sky${OF}.plt
RECPLT=${TMPPATH}rec${OF}.plt
teqc +qc -s -nav $2 $1 > $OF3
./qcplot.py ${1::8} $typ0 > $OF1
if [ $? -ne 0 ]; then
	exit -1
fi
sort -k3 -r $OF1 > $OF2 
sed -e s%skyplot.png%${1::8}sky.png% -e s%data2.txt%$OF2% -e s%ssss%$station% -e s%ddd%$doy% -e s%yyyy%$year% -e s%session%$session% -e s%ttt%$typ% $SKYTEMPLATE > $SKYPLT
gnuplot $SKYPLT
sed -e s%recplot.png%${1::8}rec.png% -e s%data2.txt%$OF2% -e s%ssss%$station% -e s%ddd%$doy% -e s%yyyy%$year% -e s%session%$session% -e s%ttt%$typ% $RECTEMPLATE > $RECPLT
gnuplot $RECPLT
# clean up
rm -f $SKYPLT $RECPLT $OF1 $OF2 $OF3
